/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lakindu;


import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Induwara Jayalath
 */
public class MySystem extends javax.swing.JFrame {

    /**
     * Creates new form System
     */
    public static int admin_no=0;
    
    public MySystem() {
        initComponents();
        showpanel("card12");
        if (admin_no==0){AdminPannel_system.setVisible(false);}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        UserPannel_System = new javax.swing.JPanel();
        in_button_Sys = new javax.swing.JButton();
        Out_button_sys = new javax.swing.JButton();
        Stock_button_sys = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        AdminPannel_system = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        SysPanel_System = new javax.swing.JPanel();
        Welcome_card = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        add_owner_pannel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        owner_name_insert = new javax.swing.JTextField();
        Owner_address_insert = new javax.swing.JTextField();
        Owner_TP_insert = new javax.swing.JTextField();
        Owner_id_insert = new javax.swing.JTextField();
        OK_InsertPPL = new javax.swing.JButton();
        add_user_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        user_name_insert1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        userame_insert = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        user_password_insert1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        OK_InsertUser = new javax.swing.JButton();
        admin_radio = new javax.swing.JRadioButton();
        user_radio = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        addItem_pannel = new javax.swing.JPanel();
        ItemName_addItem = new javax.swing.JTextField();
        Stock_addItem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Add_button_additem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserPannel_System.setBackground(new java.awt.Color(153, 153, 255));

        in_button_Sys.setText("in");
        in_button_Sys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_button_SysMouseClicked(evt);
            }
        });
        in_button_Sys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_button_SysActionPerformed(evt);
            }
        });

        Out_button_sys.setText("Out");
        Out_button_sys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Out_button_sysActionPerformed(evt);
            }
        });

        Stock_button_sys.setText("Stock");
        Stock_button_sys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stock_button_sysActionPerformed(evt);
            }
        });

        jButton1.setText("From me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("From Others");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserPannel_SystemLayout = new javax.swing.GroupLayout(UserPannel_System);
        UserPannel_System.setLayout(UserPannel_SystemLayout);
        UserPannel_SystemLayout.setHorizontalGroup(
            UserPannel_SystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPannel_SystemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserPannel_SystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_button_Sys)
                    .addComponent(Out_button_sys)
                    .addComponent(Stock_button_sys)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserPannel_SystemLayout.setVerticalGroup(
            UserPannel_SystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPannel_SystemLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(in_button_Sys)
                .addGap(44, 44, 44)
                .addComponent(Out_button_sys)
                .addGap(49, 49, 49)
                .addComponent(Stock_button_sys)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jButton2)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        getContentPane().add(UserPannel_System, java.awt.BorderLayout.LINE_START);

        jButton3.setText("Add PPL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Add User");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Dlt User");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Dlt PPL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Add item");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPannel_systemLayout = new javax.swing.GroupLayout(AdminPannel_system);
        AdminPannel_system.setLayout(AdminPannel_systemLayout);
        AdminPannel_systemLayout.setHorizontalGroup(
            AdminPannel_systemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPannel_systemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPannel_systemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        AdminPannel_systemLayout.setVerticalGroup(
            AdminPannel_systemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPannel_systemLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton3)
                .addGap(58, 58, 58)
                .addComponent(jButton4)
                .addGap(63, 63, 63)
                .addComponent(jButton5)
                .addGap(60, 60, 60)
                .addComponent(jButton6)
                .addGap(46, 46, 46)
                .addComponent(jButton7)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(AdminPannel_system, java.awt.BorderLayout.LINE_END);

        SysPanel_System.setBackground(new java.awt.Color(255, 255, 204));
        SysPanel_System.setLayout(new java.awt.CardLayout());

        Welcome_card.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Welcome To M-Audio \nStock management System");

        javax.swing.GroupLayout Welcome_cardLayout = new javax.swing.GroupLayout(Welcome_card);
        Welcome_card.setLayout(Welcome_cardLayout);
        Welcome_cardLayout.setHorizontalGroup(
            Welcome_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Welcome_cardLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
        );
        Welcome_cardLayout.setVerticalGroup(
            Welcome_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Welcome_cardLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        SysPanel_System.add(Welcome_card, "card12\n");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        SysPanel_System.add(jPanel2, "card1\n");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        SysPanel_System.add(jPanel3, "card2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        SysPanel_System.add(jPanel4, "card3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        SysPanel_System.add(jPanel5, "card4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        SysPanel_System.add(jPanel6, "card5");

        add_owner_pannel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("Owner Name");

        jLabel5.setText("Owner_adderess");

        jLabel6.setText("Owner TP");

        jLabel7.setText("Owner ID");

        OK_InsertPPL.setText("ok");
        OK_InsertPPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_InsertPPLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_owner_pannelLayout = new javax.swing.GroupLayout(add_owner_pannel);
        add_owner_pannel.setLayout(add_owner_pannelLayout);
        add_owner_pannelLayout.setHorizontalGroup(
            add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_owner_pannelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_owner_pannelLayout.createSequentialGroup()
                        .addGroup(add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(74, 74, 74)
                        .addGroup(add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Owner_TP_insert, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(Owner_id_insert)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_owner_pannelLayout.createSequentialGroup()
                        .addGroup(add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(add_owner_pannelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59))
                            .addGroup(add_owner_pannelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(owner_name_insert, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(Owner_address_insert))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_owner_pannelLayout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(OK_InsertPPL)
                .addGap(246, 246, 246))
        );
        add_owner_pannelLayout.setVerticalGroup(
            add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_owner_pannelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(owner_name_insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Owner_address_insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Owner_TP_insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(add_owner_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Owner_id_insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(OK_InsertPPL)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        SysPanel_System.add(add_owner_pannel, "card6");

        add_user_panel.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setText("Name");

        jLabel9.setText("UserName");

        jLabel10.setText("PassWord");

        jLabel11.setText("Type");

        OK_InsertUser.setText("ADD");
        OK_InsertUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_InsertUserActionPerformed(evt);
            }
        });

        buttonGroup1.add(admin_radio);
        admin_radio.setText("admin");
        admin_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_radioActionPerformed(evt);
            }
        });

        buttonGroup1.add(user_radio);
        user_radio.setSelected(true);
        user_radio.setText("user");
        user_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_radioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_user_panelLayout = new javax.swing.GroupLayout(add_user_panel);
        add_user_panel.setLayout(add_user_panelLayout);
        add_user_panelLayout.setHorizontalGroup(
            add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_user_panelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_user_panelLayout.createSequentialGroup()
                        .addGroup(add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGroup(add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(add_user_panelLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(admin_radio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(user_radio))
                            .addGroup(add_user_panelLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(user_password_insert1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_user_panelLayout.createSequentialGroup()
                        .addGroup(add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user_name_insert1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(userame_insert))))
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_user_panelLayout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(OK_InsertUser)
                .addGap(246, 246, 246))
        );
        add_user_panelLayout.setVerticalGroup(
            add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_user_panelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(user_name_insert1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(userame_insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(user_password_insert1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(add_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(admin_radio)
                    .addComponent(user_radio))
                .addGap(62, 62, 62)
                .addComponent(OK_InsertUser)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        SysPanel_System.add(add_user_panel, "card7");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        SysPanel_System.add(jPanel9, "card8");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        SysPanel_System.add(jPanel10, "card9");

        jLabel2.setText("item name");

        jLabel3.setText("Stock");

        Add_button_additem.setText("ADD");
        Add_button_additem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_button_additemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addItem_pannelLayout = new javax.swing.GroupLayout(addItem_pannel);
        addItem_pannel.setLayout(addItem_pannelLayout);
        addItem_pannelLayout.setHorizontalGroup(
            addItem_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItem_pannelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(addItem_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Add_button_additem)
                    .addGroup(addItem_pannelLayout.createSequentialGroup()
                        .addGroup(addItem_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(addItem_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemName_addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stock_addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        addItem_pannelLayout.setVerticalGroup(
            addItem_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItem_pannelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(addItem_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemName_addItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(addItem_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stock_addItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(Add_button_additem)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        SysPanel_System.add(addItem_pannel, "card13");

        getContentPane().add(SysPanel_System, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void in_button_SysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_button_SysActionPerformed
        showpanel("card1");        // TODO add your handling code here:
    }//GEN-LAST:event_in_button_SysActionPerformed

    private void Out_button_sysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Out_button_sysActionPerformed
        showpanel("card2");   // TODO add your handling code here:
    }//GEN-LAST:event_Out_button_sysActionPerformed

    private void Stock_button_sysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stock_button_sysActionPerformed
        showpanel("card3");        // TODO add your handling code here:
    }//GEN-LAST:event_Stock_button_sysActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showpanel("card4");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showpanel("card5");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        showpanel("card6");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        showpanel("card7");  
                                    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        showpanel("card8");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        showpanel("card9");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        showpanel("card13");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Add_button_additemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_button_additemActionPerformed
try
    {
        Date date = new Date();
        String str = new SimpleDateFormat("yyyy-MM-dd").format(date);
        
 
     String dbURL="jdbc:derby://localhost:1527/Laki";
     java.sql.Connection con=DriverManager.getConnection(dbURL, "induwara", "donz2014");
     Statement stmt=con.createStatement();

      String query = " insert into items (item_name, stock, owner, added_date, status)"
        + " values (?, ?, ?, ?, ?)";


      PreparedStatement preparedStmt = con.prepareStatement(query);
   
      preparedStmt.setString    (1, ItemName_addItem.getText());
      preparedStmt.setString    (2, Stock_addItem.getText());
      preparedStmt.setInt       (3, 1);
      preparedStmt.setString    (4, str);
      preparedStmt.setInt       (5, 1);

     
      preparedStmt.execute();
      
      con.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_button_additemActionPerformed

    private void OK_InsertPPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_InsertPPLActionPerformed
      try
    {
        Date date = new Date();
        String str = new SimpleDateFormat("yyyy-MM-dd").format(date);
        
 
     String dbURL="jdbc:derby://localhost:1527/Laki";
     java.sql.Connection con=DriverManager.getConnection(dbURL, "induwara", "donz2014");
     Statement stmt=con.createStatement();

      String query = " insert into owners (owner_name, owner_address, owner_tp, ID_no)"
        + " values (?, ?, ?, ?)";

int tp=Integer.parseInt(Owner_TP_insert.getText());
      PreparedStatement preparedStmt = con.prepareStatement(query);
   
      preparedStmt.setString    (1, owner_name_insert.getText());
      preparedStmt.setString    (2, Owner_address_insert.getText());
      preparedStmt.setInt       (3,  tp);
      preparedStmt.setString    (4, Owner_id_insert.getText());
      

     
      preparedStmt.execute();
      
      con.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_OK_InsertPPLActionPerformed
int selected=0;
    @SuppressWarnings("empty-statement")
    private void OK_InsertUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_InsertUserActionPerformed
             try
    {
        
 
     String dbURL="jdbc:derby://localhost:1527/Laki";
     java.sql.Connection con=DriverManager.getConnection(dbURL, "induwara", "donz2014");
     Statement stmt=con.createStatement();

      String query = " insert into usernames (name, username, password, admin_no)"
        + " values (?, ?, ?, ?)";


      PreparedStatement preparedStmt = con.prepareStatement(query);
   
      preparedStmt.setString    (1, user_name_insert1.getText());
      preparedStmt.setString    (2, userame_insert .getText());
      preparedStmt.setString    (3, user_password_insert1.getText());
      preparedStmt.setInt       (4, selected);
      

     
      preparedStmt.execute();
      
      con.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
    }
    }//GEN-LAST:event_OK_InsertUserActionPerformed

    private void admin_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_radioActionPerformed
        selected=1;        // TODO add your handling code here:
    }//GEN-LAST:event_admin_radioActionPerformed

    private void user_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_radioActionPerformed
        selected=0;       // TODO add your handling code here:
    }//GEN-LAST:event_user_radioActionPerformed

    private void in_button_SysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_button_SysMouseClicked
        showpanel("card1");        // TODO add your handling code here:
    }//GEN-LAST:event_in_button_SysMouseClicked

    /**
     * @param args the command line arguments
     */
    
    /**
     *
     * @param cname
     */
    
    public void showpanel(String cname)
    {
        CardLayout cL=(CardLayout) SysPanel_System.getLayout();
        cL.show(SysPanel_System, cname); 
    }
   
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    
     
    
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MySystem().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_button_additem;
    private javax.swing.JPanel AdminPannel_system;
    private javax.swing.JTextField ItemName_addItem;
    private javax.swing.JButton OK_InsertPPL;
    private javax.swing.JButton OK_InsertUser;
    private javax.swing.JButton Out_button_sys;
    private javax.swing.JTextField Owner_TP_insert;
    private javax.swing.JTextField Owner_address_insert;
    private javax.swing.JTextField Owner_id_insert;
    private javax.swing.JTextField Stock_addItem;
    private javax.swing.JButton Stock_button_sys;
    private javax.swing.JPanel SysPanel_System;
    private javax.swing.JPanel UserPannel_System;
    private javax.swing.JPanel Welcome_card;
    private javax.swing.JPanel addItem_pannel;
    private javax.swing.JPanel add_owner_pannel;
    private javax.swing.JPanel add_user_panel;
    private javax.swing.JRadioButton admin_radio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton in_button_Sys;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField owner_name_insert;
    private javax.swing.JTextField user_name_insert1;
    private javax.swing.JTextField user_password_insert1;
    private javax.swing.JRadioButton user_radio;
    private javax.swing.JTextField userame_insert;
    // End of variables declaration//GEN-END:variables
}
